server:
  port: 65533

spring:
  redis:
    host: 127.0.0.1
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    port: 6379
    password: H2h2828
    database: 2

logging:
  level:
    com.xkcoding: debug


